baseurl = "https://qrxnz.dev"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "qrxnz's space"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Blog"
url = "https://blog.qrxnz.dev"
weight = 1
[[menu.main]]
name = "Other Links"
url = "https://linktr.ee/qrxnz"
weight = 2
[[menu.feed]]
name = "RSS"
url = "https://blog.qrxnz.dev/index.xml"

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "Open-Source | [Github](https://github.com/qrxnz) | [Codeberg](https://codeberg.org/qrxnz)"
